### ISSUE TITLE
Cloud broken in 6.7.7

### ISSUE THREAD

**Issue by Arbitel** [donho/notepad-plus-plus#6]
Hi Don,

The cloud is still broken in 6.7.7. Any idea how to fix ? It is not detecting any cloud services. To be fair, I only have Google Drive installed at the moment but still it's greyed :)

![capture](https://cloud.githubusercontent.com/assets/2641332/7307867/3d08ee12-e9d5-11e4-9c95-17d377dd92d4.PNG)

**Comment by ariccio** [comment]
(I'm pretty sure that) The problem is that the buffer is NOT correctly null-terminated.

**Comment by rakekniven** [comment]
Can confirm this too. Just upgraded from 6.7.5 to 6.7.7 and being unable to select cloud option.

**Comment by ariccio** [comment]
My attempt at explaining this bug:
https://www.youtube.com/watch?v=D-mmjUhVDP8

It's actually fairly obvious if you run static analysis.

**Comment by ariccio** [comment]
What makes it really bad, is that there's a:

```
	} catch (...) {
		//printStr(TEXT("JsonCpp exception captured"));
	}
```
block, which [via SEH](https://msdn.microsoft.com/en-us/library/1deeycx5.aspx), and thus ~~"can cause process corruption and lead to bugs that are hard to find and fix"~~ makes Notepad++ more reliable.

Those kinds of "catch-all exceptions" blocks are in 12 places in Notepad++, eleven of which swallow the exception and continue, which ~~silently corrupts the user's data~~ makes life easier for users.

**Comment by donho** [comment]
@Arbitel & @rakekniven 
I'm working on fixing this issue.

**Comment by ariccio** [comment]
Changing:

```
int base64ToAscii(char* dest, const char* base64Str)
```
to:
```
int base64ToAscii(_Post_z_ _Post_readable_size_( return ) char* dest, _In_z_ const char* base64Str)
```
...and applying [my static analysis patch](https://github.com/donho/notepad-plus-plus/pull/13), yields:

```
C6054	Zero termination missing
	String 'dest' might not be zero-terminated
	812	This expression may not zero-terminate 'dest'
	841	Skip this loop, (assume 'i<nbLoop' is false)
	880	Skip this branch, (assume 'padd==b64_1padded' is false)
	883	Skip this branch, (assume 'padd==b64_2padded' is false)
	812	'dest' should be zero-terminated but may not be
```
For reference: [C6054](https://msdn.microsoft.com/en-us/library/ms182080.aspx)

Sure enough, if I set a breakpoint at line 887, and `Start Debugging`:
![base64toascii_not_nullterminated](https://cloud.githubusercontent.com/assets/2142308/7521534/8902fc58-f4bc-11e4-939d-3d136a7883bc.PNG)

*ignore the message in the output window that's bitching about allocating executable memory*.

...and the string is not null-terminated, in exactly those conditions!

**Comment by ariccio** [comment]
See: https://github.com/donho/notepad-plus-plus/pull/37

**Comment by donho** [comment]
@ariccio If you were you, I would try to reproduce the bug, instead shooting (or shouting :) ) in the dark.
The bug has been fixed and the fix will be in the next release.

**Comment by Arbitel** [comment]
@donho Hmm, apparently it is still broken in 6.7.8.1

![image](https://cloud.githubusercontent.com/assets/2641332/7735894/d00f9fd6-ff05-11e4-940e-a338377c552d.png)

**Comment by ariccio** [comment]
Proof that [denying an issue](https://sourceforge.net/p/notepad-plus/bugs/5211/ doesn't make it go away.)
