### ISSUE TITLE
Crashes when opening .nfo files

### ISSUE THREAD

**Issue by XSStudio** [donho/notepad-plus-plus#74]
Notepad++ crashes when opening files ending ".nfo" in Windows (you could only open the file by dragging it into N++). It's been an ancient bug...

![2015-05-15_23-07-04](https://cloud.githubusercontent.com/assets/12462351/7655628/4736342e-fb57-11e4-8b94-d92134909347.png)

**Comment by andreas-jonsson** [comment]
Works fine here. Can you provide an example file? Are you running any plugins?

**Comment by XSStudio** [comment]
That's quite strange... I just renamed an empty txt to nfo, and it seems that the bug has nothing to do with the program language. I've been bothered by this for quite a long time...

![2015-05-15_23-07-04](https://cloud.githubusercontent.com/assets/12462351/7655933/b562fc0a-fb59-11e4-8a81-5dd94d61e5d4.png)

**Comment by XSStudio** [comment]
Hah! @andreas-jonsson Thanks for the tip. I've been using HEX-Editor for quite some time. It seems to be the root of the problem. Sad we don't have a newer alternative... :(

**Comment by ariccio** [comment]
What's up with HEX-Editor? Nobody maintaining it?

**Comment by ariccio** [comment]
That's funny. The sources for HEX-Editor won't even compile correctly. All sorts of issues with undeclared identifiers (they look like obvious scoping mistakes) and iterator issues.....how the hell did it compile in the first place?

**Comment by XSStudio** [comment]
@ariccio Beats me... :(

**Comment by ariccio** [comment]
WELL, two minutes after running static analysis, I found a bug where a call to `memcpy(info->text, buffer, length)` might evaluate to `memcpy(info->text, buffer, 4294967295)`, and it's in a function called `MultiTypeCombo::decode`, which is highly suspicious.

The bug is that the return value of `WideCharToMultiByte` (an `int`) is assigned to a `UINT`, in the expression:

```
length = ::WideCharToMultiByte(codePage, 0, (WCHAR*)info->text, -1, buffer, 256, NULL, NULL) - 1;
```
....and if `WideCharToMultiByte` fails, that expression evaluates as:

```
length = - 1;
```
...and assigning `-1` to an `UINT`, well, that's 4,294,967,295.

Static analysis is truly invaluable.

**Comment by ariccio** [comment]
So I've been cleaning HEXEditor up a bit, and I'll send the changes to the author. I hope that I've fixed the problem :)

**Comment by XSStudio** [comment]
I'm not sure the author will respond to that... He/She has abandoned the project for quite a long time. But thx any way! :)

Sent from Outlook

    _____________________________

**Comment by donho** [comment]
@ariccio You fixed the bug, or you didn't fix it. There's no hope.
